### ISSUE TITLE
Add offline mode support

### ISSUE THREAD

**Issue by IlPicasso** [SquidHQ/launcher#1]
Offline mode servers would love to use this plugin too!

**Comment by Yive** [comment]
Offline mode wont be supported due to the fact it would be promoting piracy of Minecraft.

**Comment by IlPicasso** [comment]
In order to make this launcher even more popular you should consider all kind of players.

I manage a network with 2000 Players Premiums and No Premiums users which I am considering make all of them use the launcher.

You could do like MagicLauncher, where if you insert a wrong password or you do not have access to the authentication servers (because of the internet) it should let you still open the game in offline mode

**Comment by Serayne92** [comment]
We will think about it, but you have to remember the legal concerns we'd be facing if we were to do such a thing. Microsoft will most likely gun us down over something like that, and it's just not worth it to the rest of the community over the small amount of cracked servers. Like I said though, we will consider it.

**Comment by MrPowerGamerBR** [comment]
:+1: Offline mode support would help developers (when creating plugins that needs more than one user online) and users (well, you know why, not everyone is rich enough to buy Minecraft).

If offline mode support is implemented, I would switch from my server launcher to SquidHQ's launcher as soon as possible. :)

Of course, don't name this feature as "Cracked user" or "Mojang auth bypass", just name it as "Offline mode".

**Comment by IlPicasso** [comment]
I am sure having an offline mode server is not illegal, not sure about the launcher

**Comment by nathampa0909** [comment]
In my opinion, if Mojang accept servers to change online-mode to accept only premium or others, I think that putting the launcher in offline-mode too dont go against eula.

**Comment by nathampa0909** [comment]
mojang = bad
offline-mode = good for us and users
plz add offline mode support thx

**Comment by andrewkm** [comment]
We will not be supporting offline clients. If & when Mojang decides to take this seriously, this will give them a clear path to "financial damages by influencing non-premium Minecraft accounts"

Our goal is not to take away from Mojang's sales. Our goal is to give players freedom as to where they play due to the very unprofessional handling of their EULA.

**Comment by MrPowerGamerBR** [comment]
@andrewkm yeah, that makes sense, thanks for replying. :+1:
