### ISSUE TITLE
Unexpected error (Windows 10)

### ISSUE THREAD

**Issue by 4a2e532e** [SquidHQ/launcher#2]
When I try to start SquidHQ (No matter if I use the jar or the exe) it hangs at Downloading launcher for 3 minutes.
![progress](https://cloud.githubusercontent.com/assets/15034046/17493722/e5d2d05c-5db1-11e6-9b58-a6de83c498bb.PNG)

After 3 minutes I get this error message:
![error](https://cloud.githubusercontent.com/assets/15034046/17493745/fc14ae26-5db1-11e6-98e8-cae3a32e07da.PNG)

I'm using Windows 10 version 1607 and the latest version of Java and smartscreen is disabled.
This error also happens when all antivirus software is disabled.

**Comment by Yive** [comment]
Does this happen with the .exe or the .jar file? I recommend using the .jar file until the .exe file has been fixed of it's issues.

**Comment by 4a2e532e** [comment]
It happens with both of them in exactly the same way.

**Comment by 4a2e532e** [comment]
I tried running the jar from a terminal, here is the output:

`$ java -jar SquidHQ.jar
Launcher sha1: 3b9493956b376cfaa5f2a386aec620d2db13af58
Launcher signature:
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAABCAAGBQJXp1+AAAoJEIE8Muo3pY2qgxsP/2XegCMVEAOsUebCt5dfpQ53
h97f+jLL4K6UtCVSRiG+hfxV50NljBFd2sW5MXI9NckBceGjlyw5djHbfVpRi9es
NnGB+iaAs+mnRHgzTz9vQ/XReS5k2zOwoGwWEPwabDRpLAWFdJgvx9CF12fbAp3D
GY5fPNVG69iDo45GqkfYK+dxERCpLtXnsRSA2LZTk2TclqWp9ttQlLpyd34T52Y6
CXEyLzI5VQx+DSWgQH3VuLkEPakLwrYByEaI/+hcsiwIRVA898C/zfpLkb6Wvh5n
VtLxkPin5GfepnAA+R0qs8a12NAjsg+q74LGKIHm9AIcIXPkujx0xzdVFx+y8KZi
1QnW9KdsBUkEEunnDJX9sePbtLZeLKYttTDdly8Db5g80dKkm4ClKXH66ubWblaF
/IBzz/wrFZzSn22ey+1ydM1y/8Ix1wqrsPvXgVBcs1ex0KDedSCYvIqirBgY/m5i
Vrwplq41GWrgXvZF+A7sU+Dz7vvyIR5NBe6qwV2dl0Xl6O+RQmk0GTSnLQAmM2FV
kcMzjPWGnMehn4hPGkhJC/Vuv1w5IiMY76bF0f0BIqeS/BoGcHcE/naMXPOAGETZ
2zHlIriogFj5FSKRJXqWN23L4WGPzqO/DbWh0Vyk6psB3HRxgKcLmg23sBjFhdrD
K+PVD3cB0MgkKXrV0brR
=dfxL
-----END PGP SIGNATURE-----`

**Comment by coelho** [comment]
@4a2e532e Can you try downloading the file:
http://assetcdn.squidhq.com/r/3b9493956b376cfaa5f2a386aec620d2db13af58
and tell me if you have any issues?

**Comment by 4a2e532e** [comment]
This file works perfectly, thanks.

**Comment by andrewkm** [comment]
Assuming this is fixed @coelho @4a2e532e 
Closed.
