### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Crotaz** [SquidHQ/launcher#5]
![fc14ae26-5db1-11e6-98e8-cae3a32e07da](https://cloud.githubusercontent.com/assets/21056477/17694860/95204362-63ae-11e6-8556-fa42111f4b70.PNG)
Doesnt even start downloading

**Comment by Crotaz** [comment]
I am using windows 10 newest version of java and tried using this http://assetcdn.squidhq.com/r/3b9493956b376cfaa5f2a386aec620d2db13af58. Didn't work

**Comment by coelho** [comment]
What Antivirus are you running? @Crotaz

**Comment by Crotaz** [comment]
@coelho f secure and malwarebytes

**Comment by Crotaz** [comment]
I live in finland so could the country be a problem. I also tried using another computer but got the same error.

**Comment by Crotaz** [comment]
the only thing it does is it makes the .new file in the .minecraft folder

**Comment by Crotaz** [comment]
What program is this to be ran with http://assetcdn.squidhq.com/r/3b9493956b376cfaa5f2a386aec620d2db13af58.

**Comment by coelho** [comment]
Disable F-Secure, then retry.

**Comment by Crotaz** [comment]
@coelho Disabling f secure didnt help, i also tried deleting all server texture packs, normal texture packs downloaded worlds and basically every unneeded file but it still wont work

**Comment by coelho** [comment]
It is F-Secure. I've seen this before. You need to fully disable it and re-run the launcher.

**Comment by Crotaz** [comment]
ok thank you it started working

**Comment by Karrade** [comment]
This should be closed
