### ISSUE TITLE
[Unrelated] Website stats seems to be broken.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [SquidHQ/launcher#7]
I know this isn't the "SquidHQ's website issue tracker" (because that doesn't exists... right?) but I found an issue when I opened SquidHQ's website today.

![http://i.imgur.com/5F3FVqa.png](http://i.imgur.com/5F3FVqa.png)

The `In-Game Users:` and `Download Count:` are not showing the stats.

(Mentioning @Yive because it shows that he made the website)

**Comment by Yive** [comment]
It's all fixed now, I think the server just had some sort of hiccup & was returning error 500 to each request on the stats.
