### ISSUE TITLE
SquidHQ not opening!

### ISSUE THREAD

**Issue by Ruthlessbug13** [SquidHQ/launcher#8]
So i was going to play some Arkhamnetwork and i tried to open SquidHQ and nothing happened! I don`t know what to do if you need proof i can record a video but i just don`t know what to do. :(

**Comment by OutdatedVersion** [comment]
We need more information mate. Is it just not doing anything at all when you attempt running the program?

**Comment by Ruthlessbug13** [comment]
yes nothing happened`s when i open the program

**Comment by Yive** [comment]
If you're on Windows, I recommend trying to open the launcher (remember to keep an eye on the time), then open up event viewer & check if there's any errors relating to SquidHQ when you tried to open it.

**Comment by Ruthlessbug13** [comment]
The MC launcher or the SquidHQ Launcher? because it wont even install SquidHQ

**Comment by Ruthlessbug13** [comment]
I opened Event viewer and i didn`t see anything to do with SquidHQ when i open it

**Comment by Ruthlessbug13** [comment]
Ok so i this mite be a problem i checked my MC folder and there is no SquidHQ folder! so any idea why this mite be?

**Comment by OutdatedVersion** [comment]
@Ruthlessbug13, I don't really understand the issue still? Why don't we just try starting over... download the latest launcher [here](https://squidhq.com/). Be sure to select the proper launcher for your platform (I would assume Windows).

**Comment by Ruthlessbug13** [comment]
Yes windows 10 but do i delete the old SquidHQ launcher?

**Comment by Ruthlessbug13** [comment]
So i downloaded it but nothing happened at all when i opened it

**Comment by OutdatedVersion** [comment]
@Ruthlessbug13, did you see the `Opening launcher` dialogue?

**Comment by Ruthlessbug13** [comment]
All i found was a warning in the system`s that said "failed to compute the license information ()"

**Comment by Ruthlessbug13** [comment]
So i`ve been looking through the event viewer in " Window Log > Application " but can`t find any SquidHQ error`s and i even opened event viewer and then started up SquidHQ but nothing happend on the event viewer so don`t know what to do

**Comment by OutdatedVersion** [comment]
Are you able to record what's happening? As in record your screen as you do this; may help us.

**Comment by Ruthlessbug13** [comment]
Yay but all it dose is nothing i double click it and nothing happeneds so i can record it for you

**Comment by OutdatedVersion** [comment]
I don't really see how absolutely nothing is happening. Oh must get some kind of message.

**Comment by Ruthlessbug13** [comment]
Here proof of nothing happening [https://youtu.be/oHi7vDRNLu4](url)

**Comment by 4a2e532e** [comment]
What is your version of Java?

**Comment by Ruthlessbug13** [comment]
Newest verison

**Comment by 4a2e532e** [comment]
Could you please try downloading the .jar version of SquidHQ and open it from a command prompt?
This should show you the stacktrace.

**Comment by OutdatedVersion** [comment]
You could try using the `jar` instead, and running it from your terminal. Should be able to see what's going wrong then.

**Comment by Ruthlessbug13** [comment]
Lol you both said the same thing

**Comment by Ruthlessbug13** [comment]
where do i get the .jar?

**Comment by 4a2e532e** [comment]
Download the Linux version.

**Comment by Ruthlessbug13** [comment]
Ok i have the jar

**Comment by 4a2e532e** [comment]
1. Open the folder where you saved the jar
2. Hold shift and rightclick on an empty space in that folder
3. Click on Open command window here
4. Type in `java -jar SquidHQ.jar`

**Comment by Ruthlessbug13** [comment]
Ok i did and it said "Error occurred during initialization of VM" what dose that mean"
it also said "java/lang/NoClassDefFoundError:  java/lang/Object" what dose that mean?

**Comment by 4a2e532e** [comment]
Start it from Terminal again, this time using the command `java -jar SquidHQ.jar > log.txt`
This will produce a file called log.txt which contains the error message.
Post it's content here.

**Comment by Ruthlessbug13** [comment]
ok

**Comment by Ruthlessbug13** [comment]
Here "Error occurred during initialization of VM java/lang/NoClassDefFoundError: java/lang/Object"

**Comment by 4a2e532e** [comment]
Could you please open the terminal and type in `java -version` and post the output?

**Comment by Ruthlessbug13** [comment]
It just said this again "Error occurred during initialization of VM java/lang/NoClassDefFoundError: java/lang/Object"

**Comment by Ruthlessbug13** [comment]
I think i have java 8 (64-bit)

**Comment by OutdatedVersion** [comment]
@Ruthlessbug13, try reinstalling [Java](https://www.java.com/en/).

**Comment by Ruthlessbug13** [comment]
Ok i reinstalled java

**Comment by OutdatedVersion** [comment]
Now try rerunning `java -version` @Ruthlessbug13

**Comment by Ruthlessbug13** [comment]
Nope still this error "Error occurred during initialization of VM java/lang/NoClassDefFoundError: java/lang/Object"

**Comment by OutdatedVersion** [comment]
The issue arises from an invalid Java installation. Be sure you _completely_ uninstall Java then run the proper installer.

**Comment by 4a2e532e** [comment]
Or there is something wrong with your path.
Could you please run the command `path` in a terminal and post the output?

**Comment by Ruthlessbug13** [comment]
here is the output " PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jre1.8.0_45\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\TheGr\AppData\Local\Microsoft\WindowsApps; '

**Comment by Ruthlessbug13** [comment]
So find anything that could help me?

**Comment by 4a2e532e** [comment]
Please execute the following to commands and post the output:
1. `C:\Program Files\Java\jre1.8.0_45\bin\java.exe" -version`
2. `C:\ProgramData\Oracle\Java\javapath\java.exe -version`

**Comment by Ruthlessbug13** [comment]
First command said " 'C:\Program' is not recognized as an internal or external command, operable program or batch file. "
Second command said " Error occurred during initialization of VM java/lang/NoClassDefFoundError: java/lang/Object "

**Comment by jaime29010** [comment]
I think that your runtime is corrupted, reinstall Java

**Comment by Ruthlessbug13** [comment]
ive tried millions of times it dosnt help at all unless you want to delete java and reinstall it?

**Comment by Ruthlessbug13** [comment]
now will this corrupt any games?

**Comment by jaime29010** [comment]
Yeah, completly uninstall Java (make sure the directories of Java are deleted) and install the latest version.

**Comment by Ruthlessbug13** [comment]
so delete all dirs to java from all games and stuff

**Comment by Ruthlessbug13** [comment]
ok

**Comment by Ruthlessbug13** [comment]
what about JDK? do i delete that to?

**Comment by jaime29010** [comment]
One thing, this is not a chat, edit a message instead of doing what you are doing.

Uninstall both the JDK and the JRE, anything that has something to do with Oracle Java

**Comment by Ruthlessbug13** [comment]
it is now reinstalled. what now?

**Comment by jaime29010** [comment]
@Ruthlessbug13 close the issue

**Comment by Ruthlessbug13** [comment]
close
